### ISSUE TITLE
slave functionality.

### ISSUE THREAD

**Issue by seekaddo** [openxc/uds-c#11]
Hi,

I am trying to use this library on a slave device(MCU) to receive request from a master device(my computer).
Is it possible to use this library to receive request from a master device? I am asking because i can't seem to find any test code for a slave device. Is this library for master?

Exapmle:
A Client device waits for uds request, processes it and send the response in uds form. The issue is
which funtion will it use to create a uds response and send it to the master and wait again for another request.

Thanks for support.

**Comment by emarsman** [comment]
I'm not sure what you mean. CAN is not a master/slave protocol. It self arbitrates based on priority of message IDs. 

Here is where we use the UDS library: https://github.com/openxc/vi-firmware/blob/45eeb2ac664b8f5969a928c31262de01626e0d3b/src/diagnostics.cpp.

We can send a request and pair it with the response. We can queue up multiple requests. It also depends on the iso-tp library. Let me know if you have any further questions.
