### ISSUE TITLE
it feels like impossible to merge

### ISSUE THREAD

**Issue by ajaybhargav** [openxc/uds-c#19]
I am trying to merge master branch with openxc/uds-c I keep on getting conflict error

both modified:   deps/isotp-c

I do not understand how to resolve this. how do you update your sources?

**Comment by emarsman** [comment]
I don't know what commands you're running or what your conflicts are, but isotp-c is a submodule for uds-c so you will need to work with Git submodules: https://git-scm.com/book/en/v2/Git-Tools-Submodules.

**Comment by ajaybhargav** [comment]
Sorry for not updating here, My submodule master diverged (I don't know how) from origin/master which made it fail to merge. I fixed it. Sorry to bother.
